import type { neon } from '@neondatabase/serverless';

export const AUTH_SCHEMA_VERSION = 3;

type Sql = ReturnType<typeof neon>;

export async function initializeAuthSchema(sql: Sql): Promise<void> {
  await sql.transaction((tx) => [
    tx`SELECT pg_advisory_xact_lock(18521401)`,
    tx`
      CREATE TABLE IF NOT EXISTS auth_schema_migrations (
        version integer PRIMARY KEY,
        applied_at timestamptz NOT NULL DEFAULT now()
      )`,
    tx`
      DO $$
      DECLARE newest integer;
      BEGIN
        SELECT max(version) INTO newest FROM auth_schema_migrations;
        IF newest IS NOT NULL AND newest > 3 THEN
          RAISE EXCEPTION 'auth schema version % is newer than supported version 3', newest;
        END IF;
      END $$`,
    tx`
      CREATE TABLE IF NOT EXISTS users (
        id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 2) PRIMARY KEY,
        username text NOT NULL UNIQUE,
        password_hash text,
        role text NOT NULL DEFAULT 'member' CHECK (role IN ('owner', 'member')),
        can_find boolean NOT NULL DEFAULT true,
        can_read boolean NOT NULL DEFAULT false,
        can_download boolean NOT NULL DEFAULT false,
        created_via_invite_id integer,
        disabled_at timestamptz,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        CHECK (username ~ '^[a-z][a-z0-9_]{2,31}$'),
        CHECK (
          (id = 1 AND username = 'owner' AND role = 'owner'
            AND password_hash IS NULL AND disabled_at IS NULL
            AND can_find AND can_read AND can_download)
          OR
          (id > 1 AND username <> 'owner' AND role = 'member'
            AND password_hash IS NOT NULL)
        ),
        CHECK (NOT can_read OR can_find),
        CHECK (NOT can_download OR (can_find AND can_read))
      )`,
    tx`
      INSERT INTO users (id, username, role, can_find, can_read, can_download)
      VALUES (1, 'owner', 'owner', true, true, true)
      ON CONFLICT (id) DO NOTHING`,
    tx`
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM users
          WHERE id = 1 AND username = 'owner' AND role = 'owner'
            AND password_hash IS NULL AND disabled_at IS NULL
            AND can_find AND can_read AND can_download
        ) THEN
          RAISE EXCEPTION 'users.id=1 conflicts with the fixed owner identity';
        END IF;
        IF EXISTS (SELECT 1 FROM users WHERE username = 'owner' AND id <> 1) THEN
          RAISE EXCEPTION 'username owner conflicts with the fixed owner identity';
        END IF;
      END $$`,
    tx`
      CREATE TABLE IF NOT EXISTS auth_settings (
        id integer PRIMARY KEY CHECK (id = 1),
        members_enabled boolean NOT NULL DEFAULT false,
        registration_mode text NOT NULL DEFAULT 'closed'
          CHECK (registration_mode IN ('closed', 'open', 'invite')),
        updated_at timestamptz NOT NULL DEFAULT now()
      )`,
    tx`INSERT INTO auth_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING`,
    tx`
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM auth_settings
          WHERE id = 1 AND members_enabled = false AND registration_mode = 'closed'
        ) THEN
          RAISE EXCEPTION 'auth settings must remain closed during A01 initialization';
        END IF;
      END $$`,
    tx`
      CREATE TABLE IF NOT EXISTS sessions (
        token_hash char(64) PRIMARY KEY CHECK (token_hash ~ '^[0-9a-f]{64}$'),
        user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        auth_method text NOT NULL CHECK (auth_method IN ('password', 'owner_token')),
        owner_credential_tag char(64),
        created_at timestamptz NOT NULL DEFAULT now(),
        expires_at timestamptz NOT NULL,
        CHECK (expires_at > created_at),
        CHECK ((auth_method = 'owner_token') = (user_id = 1)),
        CHECK (
          (auth_method = 'owner_token' AND owner_credential_tag IS NOT NULL)
          OR (auth_method = 'password' AND owner_credential_tag IS NULL)
        )
      )`,
    tx`
      CREATE INDEX IF NOT EXISTS sessions_user_created_idx
      ON sessions (user_id, created_at DESC)`,
    tx`CREATE INDEX IF NOT EXISTS sessions_expires_idx ON sessions (expires_at)`,
    tx`
      CREATE TABLE IF NOT EXISTS auth_rate_limits (
        scope text NOT NULL,
        key_hash char(64) NOT NULL,
        window_start timestamptz NOT NULL,
        attempts integer NOT NULL CHECK (attempts >= 0),
        expires_at timestamptz NOT NULL,
        PRIMARY KEY (scope, key_hash, window_start)
      )`,
    tx`
      CREATE INDEX IF NOT EXISTS auth_rate_limits_expires_idx
      ON auth_rate_limits (expires_at)`,
    tx`
      INSERT INTO auth_schema_migrations (version)
      VALUES (1)
      ON CONFLICT (version) DO NOTHING`,
    tx`
      INSERT INTO auth_schema_migrations (version)
      VALUES (2)
      ON CONFLICT (version) DO NOTHING`,
    tx`
      DO $$
      DECLARE profile_default text;
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM auth_schema_migrations WHERE version = 3) AND (
          to_regclass('profile') IS NULL
          OR to_regclass('recommendations') IS NULL
          OR to_regclass('feedback') IS NULL
        ) THEN
          RAISE EXCEPTION 'personal data migration requires profile, recommendations, and feedback tables';
        END IF;

        IF NOT EXISTS (SELECT 1 FROM auth_schema_migrations WHERE version = 3)
          AND EXISTS (SELECT 1 FROM profile WHERE id <> 1) THEN
          RAISE EXCEPTION 'profile contains an unexpected non-owner id';
        END IF;

        SELECT pg_get_expr(d.adbin, d.adrelid)
          INTO profile_default
        FROM pg_attribute a
        LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
        WHERE a.attrelid = 'profile'::regclass AND a.attname = 'id' AND NOT a.attisdropped;
        IF NOT EXISTS (SELECT 1 FROM auth_schema_migrations WHERE version = 3)
          AND (profile_default IS NULL OR profile_default NOT IN ('1', '1::integer')) THEN
          RAISE EXCEPTION 'profile.id default drifted from owner id 1: %', profile_default;
        END IF;

        IF NOT EXISTS (SELECT 1 FROM auth_schema_migrations WHERE version = 3) AND NOT EXISTS (
          SELECT 1 FROM pg_constraint
          WHERE conrelid = 'recommendations'::regclass AND contype = 'u'
            AND pg_get_constraintdef(oid) = 'UNIQUE (book_id, query)'
        ) THEN
          RAISE EXCEPTION 'recommendations legacy table unique constraint has drifted';
        END IF;
        IF NOT EXISTS (SELECT 1 FROM auth_schema_migrations WHERE version = 3) AND NOT EXISTS (
          SELECT 1 FROM pg_indexes
          WHERE schemaname = current_schema()
            AND tablename = 'recommendations'
            AND indexname = 'recommendations_book_query_idx'
            AND indexdef LIKE 'CREATE UNIQUE INDEX % ON %.recommendations USING btree (book_id, query)'
        ) THEN
          RAISE EXCEPTION 'recommendations legacy explicit unique index has drifted';
        END IF;
      END $$`,
    tx`ALTER TABLE profile ALTER COLUMN id DROP DEFAULT`,
    tx`
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'profile'::regclass AND conname = 'profile_user_fk') THEN
          ALTER TABLE profile ADD CONSTRAINT profile_user_fk FOREIGN KEY (id) REFERENCES users(id);
        END IF;
      END $$`,
    tx`ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS user_id integer DEFAULT 1`,
    tx`UPDATE recommendations SET user_id = 1 WHERE user_id IS NULL`,
    tx`ALTER TABLE recommendations ALTER COLUMN user_id SET DEFAULT 1, ALTER COLUMN user_id SET NOT NULL`,
    tx`
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'recommendations'::regclass AND conname = 'recommendations_user_fk') THEN
          ALTER TABLE recommendations ADD CONSTRAINT recommendations_user_fk FOREIGN KEY (user_id) REFERENCES users(id);
        END IF;
      END $$`,
    tx`CREATE INDEX IF NOT EXISTS recommendations_user_created_idx ON recommendations (user_id, created_at DESC)`,
    tx`CREATE UNIQUE INDEX IF NOT EXISTS recommendations_user_book_query_idx ON recommendations (user_id, book_id, query)`,
    tx`ALTER TABLE feedback ADD COLUMN IF NOT EXISTS user_id integer DEFAULT 1`,
    tx`UPDATE feedback SET user_id = 1 WHERE user_id IS NULL`,
    tx`ALTER TABLE feedback ALTER COLUMN user_id SET DEFAULT 1, ALTER COLUMN user_id SET NOT NULL`,
    tx`
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'feedback'::regclass AND conname = 'feedback_user_fk') THEN
          ALTER TABLE feedback ADD CONSTRAINT feedback_user_fk FOREIGN KEY (user_id) REFERENCES users(id);
        END IF;
      END $$`,
    tx`CREATE INDEX IF NOT EXISTS feedback_user_created_idx ON feedback (user_id, created_at DESC)`,
    tx`
      INSERT INTO auth_schema_migrations (version)
      VALUES (3)
      ON CONFLICT (version) DO NOTHING`,
  ]);
}
