import { describe, expect, it } from 'vitest';
import { AUTH_SCHEMA_VERSION, initializeAuthSchema } from './auth-store';

type Query = { text: string };

function fakeSql() {
  const batches: Query[][] = [];
  const tx = (parts: TemplateStringsArray, ...values: unknown[]): Query => ({
    text: parts.reduce((text, part, index) => text + part + (index < values.length ? '?' : ''), ''),
  });
  return {
    batches,
    sql: {
      transaction: async (builder: (query: typeof tx) => Query[]) => {
        batches.push(builder(tx));
        return [];
      },
    },
  };
}

describe('auth schema initialization', () => {
  it('defines a versioned, locked, closed-by-default owner skeleton', async () => {
    const fake = fakeSql();
    await initializeAuthSchema(fake.sql as never);
    const text = fake.batches[0].map((query) => query.text).join('\n');
    expect(AUTH_SCHEMA_VERSION).toBe(1);
    expect(text).toContain('pg_advisory_xact_lock');
    expect(text).toContain('GENERATED BY DEFAULT AS IDENTITY (START WITH 2)');
    expect(text).toContain("VALUES (1, 'owner', 'owner', true, true, true)");
    expect(text).toContain("registration_mode text NOT NULL DEFAULT 'closed'");
    expect(text).toContain('members_enabled boolean NOT NULL DEFAULT false');
    expect(text).toContain('conflicts with the fixed owner identity');
    expect(text).not.toContain('DATABASE_URL');
  });

  it('uses the same idempotent transaction for repeated and concurrent initialization', async () => {
    const fake = fakeSql();
    await Promise.all([initializeAuthSchema(fake.sql as never), initializeAuthSchema(fake.sql as never)]);
    expect(fake.batches).toHaveLength(2);
    expect(fake.batches[0].map((query) => query.text)).toEqual(fake.batches[1].map((query) => query.text));
    for (const batch of fake.batches) expect(batch.every((query) => !/CREATE TABLE (?!IF NOT EXISTS)/.test(query.text))).toBe(true);
  });
});
