import type { neon } from '@neondatabase/serverless';

export const AUTH_SCHEMA_VERSION = 1;

type Sql = ReturnType<typeof neon>;

export async function initializeAuthSchema(sql: Sql): Promise<void> {
  await sql.transaction((tx) => [
    tx`SELECT pg_advisory_xact_lock(18521401)`,
    tx`
      CREATE TABLE IF NOT EXISTS auth_schema_migrations (
        version integer PRIMARY KEY,
        applied_at timestamptz NOT NULL DEFAULT now()
      )`,
    tx`
      DO $$
      DECLARE newest integer;
      BEGIN
        SELECT max(version) INTO newest FROM auth_schema_migrations;
        IF newest IS NOT NULL AND newest > 1 THEN
          RAISE EXCEPTION 'auth schema version % is newer than supported version 1', newest;
        END IF;
      END $$`,
    tx`
      CREATE TABLE IF NOT EXISTS users (
        id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 2) PRIMARY KEY,
        username text NOT NULL UNIQUE,
        password_hash text,
        role text NOT NULL DEFAULT 'member' CHECK (role IN ('owner', 'member')),
        can_find boolean NOT NULL DEFAULT true,
        can_read boolean NOT NULL DEFAULT false,
        can_download boolean NOT NULL DEFAULT false,
        created_via_invite_id integer,
        disabled_at timestamptz,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        CHECK (username ~ '^[a-z][a-z0-9_]{2,31}$'),
        CHECK (
          (id = 1 AND username = 'owner' AND role = 'owner'
            AND password_hash IS NULL AND disabled_at IS NULL
            AND can_find AND can_read AND can_download)
          OR
          (id > 1 AND username <> 'owner' AND role = 'member'
            AND password_hash IS NOT NULL)
        ),
        CHECK (NOT can_read OR can_find),
        CHECK (NOT can_download OR (can_find AND can_read))
      )`,
    tx`
      INSERT INTO users (id, username, role, can_find, can_read, can_download)
      VALUES (1, 'owner', 'owner', true, true, true)
      ON CONFLICT (id) DO NOTHING`,
    tx`
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM users
          WHERE id = 1 AND username = 'owner' AND role = 'owner'
            AND password_hash IS NULL AND disabled_at IS NULL
            AND can_find AND can_read AND can_download
        ) THEN
          RAISE EXCEPTION 'users.id=1 conflicts with the fixed owner identity';
        END IF;
        IF EXISTS (SELECT 1 FROM users WHERE username = 'owner' AND id <> 1) THEN
          RAISE EXCEPTION 'username owner conflicts with the fixed owner identity';
        END IF;
      END $$`,
    tx`
      CREATE TABLE IF NOT EXISTS auth_settings (
        id integer PRIMARY KEY CHECK (id = 1),
        members_enabled boolean NOT NULL DEFAULT false,
        registration_mode text NOT NULL DEFAULT 'closed'
          CHECK (registration_mode IN ('closed', 'open', 'invite')),
        updated_at timestamptz NOT NULL DEFAULT now()
      )`,
    tx`INSERT INTO auth_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING`,
    tx`
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM auth_settings
          WHERE id = 1 AND members_enabled = false AND registration_mode = 'closed'
        ) THEN
          RAISE EXCEPTION 'auth settings must remain closed during A01 initialization';
        END IF;
      END $$`,
    tx`
      INSERT INTO auth_schema_migrations (version)
      VALUES (1)
      ON CONFLICT (version) DO NOTHING`,
  ]);
}
