import type { neon } from '@neondatabase/serverless';

export const AUTH_SCHEMA_VERSION = 2;

type Sql = ReturnType<typeof neon>;

export async function initializeAuthSchema(sql: Sql): Promise<void> {
  await sql.transaction((tx) => [
    tx`SELECT pg_advisory_xact_lock(18521401)`,
    tx`
      CREATE TABLE IF NOT EXISTS auth_schema_migrations (
        version integer PRIMARY KEY,
        applied_at timestamptz NOT NULL DEFAULT now()
      )`,
    tx`
      DO $$
      DECLARE newest integer;
      BEGIN
        SELECT max(version) INTO newest FROM auth_schema_migrations;
        IF newest IS NOT NULL AND newest > 2 THEN
          RAISE EXCEPTION 'auth schema version % is newer than supported version 2', newest;
        END IF;
      END $$`,
    tx`
      CREATE TABLE IF NOT EXISTS users (
        id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 2) PRIMARY KEY,
        username text NOT NULL UNIQUE,
        password_hash text,
        role text NOT NULL DEFAULT 'member' CHECK (role IN ('owner', 'member')),
        can_find boolean NOT NULL DEFAULT true,
        can_read boolean NOT NULL DEFAULT false,
        can_download boolean NOT NULL DEFAULT false,
        created_via_invite_id integer,
        disabled_at timestamptz,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        CHECK (username ~ '^[a-z][a-z0-9_]{2,31}$'),
        CHECK (
          (id = 1 AND username = 'owner' AND role = 'owner'
            AND password_hash IS NULL AND disabled_at IS NULL
            AND can_find AND can_read AND can_download)
          OR
          (id > 1 AND username <> 'owner' AND role = 'member'
            AND password_hash IS NOT NULL)
        ),
        CHECK (NOT can_read OR can_find),
        CHECK (NOT can_download OR (can_find AND can_read))
      )`,
    tx`
      INSERT INTO users (id, username, role, can_find, can_read, can_download)
      VALUES (1, 'owner', 'owner', true, true, true)
      ON CONFLICT (id) DO NOTHING`,
    tx`
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM users
          WHERE id = 1 AND username = 'owner' AND role = 'owner'
            AND password_hash IS NULL AND disabled_at IS NULL
            AND can_find AND can_read AND can_download
        ) THEN
          RAISE EXCEPTION 'users.id=1 conflicts with the fixed owner identity';
        END IF;
        IF EXISTS (SELECT 1 FROM users WHERE username = 'owner' AND id <> 1) THEN
          RAISE EXCEPTION 'username owner conflicts with the fixed owner identity';
        END IF;
      END $$`,
    tx`
      CREATE TABLE IF NOT EXISTS auth_settings (
        id integer PRIMARY KEY CHECK (id = 1),
        members_enabled boolean NOT NULL DEFAULT false,
        registration_mode text NOT NULL DEFAULT 'closed'
          CHECK (registration_mode IN ('closed', 'open', 'invite')),
        updated_at timestamptz NOT NULL DEFAULT now()
      )`,
    tx`INSERT INTO auth_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING`,
    tx`
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM auth_settings
          WHERE id = 1 AND members_enabled = false AND registration_mode = 'closed'
        ) THEN
          RAISE EXCEPTION 'auth settings must remain closed during A01 initialization';
        END IF;
      END $$`,
    tx`
      CREATE TABLE IF NOT EXISTS sessions (
        token_hash char(64) PRIMARY KEY CHECK (token_hash ~ '^[0-9a-f]{64}$'),
        user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        auth_method text NOT NULL CHECK (auth_method IN ('password', 'owner_token')),
        owner_credential_tag char(64),
        created_at timestamptz NOT NULL DEFAULT now(),
        expires_at timestamptz NOT NULL,
        CHECK (expires_at > created_at),
        CHECK ((auth_method = 'owner_token') = (user_id = 1)),
        CHECK (
          (auth_method = 'owner_token' AND owner_credential_tag IS NOT NULL)
          OR (auth_method = 'password' AND owner_credential_tag IS NULL)
        )
      )`,
    tx`
      CREATE INDEX IF NOT EXISTS sessions_user_created_idx
      ON sessions (user_id, created_at DESC)`,
    tx`CREATE INDEX IF NOT EXISTS sessions_expires_idx ON sessions (expires_at)`,
    tx`
      CREATE TABLE IF NOT EXISTS auth_rate_limits (
        scope text NOT NULL,
        key_hash char(64) NOT NULL,
        window_start timestamptz NOT NULL,
        attempts integer NOT NULL CHECK (attempts >= 0),
        expires_at timestamptz NOT NULL,
        PRIMARY KEY (scope, key_hash, window_start)
      )`,
    tx`
      CREATE INDEX IF NOT EXISTS auth_rate_limits_expires_idx
      ON auth_rate_limits (expires_at)`,
    tx`
      INSERT INTO auth_schema_migrations (version)
      VALUES (1)
      ON CONFLICT (version) DO NOTHING`,
    tx`
      INSERT INTO auth_schema_migrations (version)
      VALUES (2)
      ON CONFLICT (version) DO NOTHING`,
  ]);
}
