import { describe, expect, it } from 'vitest';
import { AUTH_SCHEMA_VERSION, initializeAuthSchema } from './auth-store';

type Query = { text: string };

function fakeSql() {
  const batches: Query[][] = [];
  const tx = (parts: TemplateStringsArray, ...values: unknown[]): Query => ({
    text: parts.reduce((text, part, index) => text + part + (index < values.length ? '?' : ''), ''),
  });
  return {
    batches,
    sql: {
      transaction: async (builder: (query: typeof tx) => Query[]) => {
        batches.push(builder(tx));
        return [];
      },
    },
  };
}

describe('auth schema initialization', () => {
  it('defines a versioned, locked, closed-by-default owner skeleton', async () => {
    const fake = fakeSql();
    await initializeAuthSchema(fake.sql as never);
    const text = fake.batches[0].map((query) => query.text).join('\n');
    expect(AUTH_SCHEMA_VERSION).toBe(5);
    expect(text).toContain('pg_advisory_xact_lock');
    expect(text).toContain('GENERATED BY DEFAULT AS IDENTITY (START WITH 2)');
    expect(text).toContain("VALUES (1, 'owner', 'owner', true, true, true)");
    expect(text).toContain("registration_mode text NOT NULL DEFAULT 'closed'");
    expect(text).toContain('members_enabled boolean NOT NULL DEFAULT false');
    expect(text).toContain('conflicts with the fixed owner identity');
    expect(text).not.toContain('DATABASE_URL');
  });

  it('adds version 2 sessions and rate limit tables without dropping history', async () => {
    const fake = fakeSql();
    await initializeAuthSchema(fake.sql as never);
    const text = fake.batches[0].map((query) => query.text).join('\n');
    expect(text).toContain('CREATE TABLE IF NOT EXISTS sessions');
    expect(text).toContain("token_hash char(64) PRIMARY KEY CHECK (token_hash ~ '^[0-9a-f]{64}$')");
    expect(text).toContain("CHECK (auth_method IN ('password', 'owner_token'))");
    expect(text).toContain('CHECK ((auth_method = \'owner_token\') = (user_id = 1))');
    expect(text).toContain('sessions_user_created_idx');
    expect(text).toContain('sessions_expires_idx');
    expect(text).toContain('CREATE TABLE IF NOT EXISTS auth_rate_limits');
    expect(text).toContain('PRIMARY KEY (scope, key_hash, window_start)');
    expect(text).toContain('auth_rate_limits_expires_idx');
    expect(text).toContain('VALUES (2)');
    expect(text).toContain('newer than supported version 5');
    // 幂等扩展：不删表、不删列、不动 v1 结构。
    expect(text).not.toMatch(/DROP (TABLE|COLUMN)/);
    expect(text).toContain('DROP CONSTRAINT %I');
    expect(text).toContain('DROP INDEX %I.%I');
  });

  it('uses the same idempotent transaction for repeated and concurrent initialization', async () => {
    const fake = fakeSql();
    await Promise.all([initializeAuthSchema(fake.sql as never), initializeAuthSchema(fake.sql as never)]);
    expect(fake.batches).toHaveLength(2);
    expect(fake.batches[0].map((query) => query.text)).toEqual(fake.batches[1].map((query) => query.text));
    for (const batch of fake.batches) {
      expect(batch[0].text).toContain('pg_advisory_xact_lock');
      expect(batch.map((q) => q.text).join(' ')).toContain('IF NOT EXISTS (SELECT 1 FROM auth_schema_migrations WHERE version = 4)');
    }
  });

  it('adds the owner-compatible personal data migration in the locked transaction', async () => {
    const fake = fakeSql();
    await initializeAuthSchema(fake.sql as never);
    const text = fake.batches[0].map((query) => query.text).join('\n');
    expect(text).toContain("to_regclass('profile')");
    expect(text).toContain('profile contains an unexpected non-owner id');
    expect(text).toContain('recommendations legacy table unique constraint has drifted');
    expect(text).toContain('recommendations legacy explicit unique index has drifted');
    expect(text).toContain('auth_schema_migrations WHERE version = 3');
    expect(text).toContain('ALTER TABLE profile ALTER COLUMN id DROP DEFAULT');
    expect(text).toContain('profile_user_fk');
    expect(text).toContain('recommendations_user_fk');
    expect(text).toContain('feedback_user_fk');
    expect(text).toContain('recommendations_user_book_query_idx');
    expect(text).toContain('recommendations_book_query_idx');
    expect(text).toContain('VALUES (3)');
    expect(text).toContain('newer than supported version 5');
    expect(text).not.toMatch(/DROP (TABLE|COLUMN)/);
    expect(text).toContain('DROP CONSTRAINT %I');
    expect(text).toContain('DROP INDEX %I.%I');
  });

  it('adds download ownership and fails closed on duplicate active work without deleting rows', async () => {
    const fake = fakeSql();
    await initializeAuthSchema(fake.sql as never);
    const text = fake.batches[0].map((query) => query.text).join('\n');
    expect(text).toContain('ALTER TABLE download_tasks ADD COLUMN IF NOT EXISTS user_id integer');
    expect(text).toContain('UPDATE download_tasks SET user_id = 1 WHERE user_id IS NULL');
    expect(text).toContain('download_tasks_user_fk');
    expect(text).toContain('CREATE UNIQUE INDEX download_tasks_active_book_idx ON download_tasks (book_id)');
    expect(text).toContain("WHERE status IN ('pending', 'running')");
    expect(text).not.toContain('DELETE FROM download_tasks');
    expect(text).toContain('INSERT INTO auth_schema_migrations (version) VALUES (5)');
  });
});
