-- Canonical schema at application commit f48299b.
-- Executed as one statement inside the runner's transaction; do not add BEGIN/COMMIT here.

CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 2) PRIMARY KEY,
  username text NOT NULL UNIQUE,
  password_hash text,
  role text NOT NULL DEFAULT 'member' CHECK (role IN ('owner', 'member')),
  can_find boolean NOT NULL DEFAULT true,
  can_read boolean NOT NULL DEFAULT false,
  can_download boolean NOT NULL DEFAULT false,
  created_via_invite_id integer,
  disabled_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (username ~ '^[a-z][a-z0-9_]{2,31}$'),
  CHECK ((id = 1 AND username = 'owner' AND role = 'owner' AND password_hash IS NULL
      AND disabled_at IS NULL AND can_find AND can_read AND can_download)
    OR (id > 1 AND username <> 'owner' AND role = 'member' AND password_hash IS NOT NULL)),
  CHECK (NOT can_read OR can_find),
  CHECK (NOT can_download OR (can_find AND can_read))
);
INSERT INTO users (id, username, role, can_find, can_read, can_download)
VALUES (1, 'owner', 'owner', true, true, true) ON CONFLICT (id) DO NOTHING;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM users WHERE id=1 AND username='owner' AND role='owner'
    AND password_hash IS NULL AND disabled_at IS NULL AND can_find AND can_read AND can_download) THEN
    RAISE EXCEPTION 'users.id=1 conflicts with fixed owner identity';
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS auth_schema_migrations (
  version integer PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS auth_settings (
  id integer PRIMARY KEY CHECK (id=1), members_enabled boolean NOT NULL DEFAULT false,
  registration_mode text NOT NULL DEFAULT 'closed' CHECK (registration_mode IN ('closed','open','invite')),
  updated_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO auth_settings(id) VALUES (1) ON CONFLICT (id) DO NOTHING;
CREATE TABLE IF NOT EXISTS sessions (
  token_hash char(64) PRIMARY KEY CHECK (token_hash ~ '^[0-9a-f]{64}$'),
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  auth_method text NOT NULL CHECK (auth_method IN ('password','owner_token')),
  owner_credential_tag char(64), created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL, CHECK (expires_at > created_at),
  CHECK ((auth_method='owner_token') = (user_id=1)),
  CHECK ((auth_method='owner_token' AND owner_credential_tag IS NOT NULL)
      OR (auth_method='password' AND owner_credential_tag IS NULL))
);
CREATE INDEX IF NOT EXISTS sessions_user_created_idx ON sessions(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS sessions_expires_idx ON sessions(expires_at);
CREATE TABLE IF NOT EXISTS auth_rate_limits (
  scope text NOT NULL, key_hash char(64) NOT NULL, window_start timestamptz NOT NULL,
  attempts integer NOT NULL CHECK (attempts >= 0), expires_at timestamptz NOT NULL,
  PRIMARY KEY(scope,key_hash,window_start)
);
CREATE INDEX IF NOT EXISTS auth_rate_limits_expires_idx ON auth_rate_limits(expires_at);

CREATE TABLE IF NOT EXISTS profile (
  id int PRIMARY KEY CONSTRAINT profile_user_fk REFERENCES users(id),
  seeds jsonb NOT NULL DEFAULT '[]', content text NOT NULL DEFAULT '',
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE profile ALTER COLUMN id DROP DEFAULT;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM profile WHERE id <> 1)
     AND NOT EXISTS (SELECT 1 FROM auth_schema_migrations WHERE version >= 3) THEN
    RAISE EXCEPTION 'unversioned profile ownership is ambiguous; record ids: %',
      (SELECT string_agg(id::text, ',' ORDER BY id) FROM profile WHERE id <> 1);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='profile'::regclass
      AND contype='f' AND confrelid='users'::regclass) THEN
    ALTER TABLE profile ADD CONSTRAINT profile_user_fk FOREIGN KEY(id) REFERENCES users(id);
  END IF;
END $$;
INSERT INTO profile(id) VALUES(1) ON CONFLICT(id) DO NOTHING;

CREATE TABLE IF NOT EXISTS books (
  id serial PRIMARY KEY, title text NOT NULL, author text NOT NULL, douban_id text,
  douban_rating float8, douban_rating_count int, meta jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS books_title_author_idx ON books(lower(title),lower(author));

CREATE TABLE IF NOT EXISTS recommendations (
  id serial PRIMARY KEY, user_id int NOT NULL CONSTRAINT recommendations_user_fk REFERENCES users(id),
  book_id int NOT NULL REFERENCES books(id), query text NOT NULL, match_score float8,
  hit_likes jsonb, risks text, reason text, status text NOT NULL DEFAULT 'new',
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS user_id int;
UPDATE recommendations SET user_id=1 WHERE user_id IS NULL;
ALTER TABLE recommendations ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE recommendations ALTER COLUMN user_id DROP DEFAULT;
DO $$ DECLARE item record; BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='recommendations'::regclass
      AND contype='f' AND confrelid='users'::regclass AND conkey=ARRAY[(SELECT attnum FROM pg_attribute
        WHERE attrelid='recommendations'::regclass AND attname='user_id')]::smallint[]) THEN
    ALTER TABLE recommendations ADD CONSTRAINT recommendations_user_fk FOREIGN KEY(user_id) REFERENCES users(id);
  END IF;
  FOR item IN SELECT conname FROM pg_constraint WHERE conrelid='recommendations'::regclass AND contype='u'
    AND pg_get_constraintdef(oid)='UNIQUE (book_id, query)'
  LOOP EXECUTE format('ALTER TABLE recommendations DROP CONSTRAINT %I',item.conname); END LOOP;
  FOR item IN SELECT indexname FROM pg_indexes WHERE schemaname=current_schema() AND tablename='recommendations'
    AND indexdef ~ 'UNIQUE INDEX .* \(book_id, query\)'
  LOOP EXECUTE format('DROP INDEX IF EXISTS %I',item.indexname); END LOOP;
END $$;
CREATE INDEX IF NOT EXISTS recommendations_user_created_idx ON recommendations(user_id,created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS recommendations_user_book_query_idx ON recommendations(user_id,book_id,query);

CREATE TABLE IF NOT EXISTS feedback (
  id serial PRIMARY KEY, user_id int NOT NULL CONSTRAINT feedback_user_fk REFERENCES users(id),
  book_id int NOT NULL REFERENCES books(id), status text NOT NULL, note text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS user_id int;
UPDATE feedback SET user_id=1 WHERE user_id IS NULL;
ALTER TABLE feedback ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE feedback ALTER COLUMN user_id DROP DEFAULT;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='feedback'::regclass
      AND contype='f' AND confrelid='users'::regclass AND conkey=ARRAY[(SELECT attnum FROM pg_attribute
        WHERE attrelid='feedback'::regclass AND attname='user_id')]::smallint[]) THEN
    ALTER TABLE feedback ADD CONSTRAINT feedback_user_fk FOREIGN KEY(user_id) REFERENCES users(id);
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS feedback_user_created_idx ON feedback(user_id,created_at DESC);

CREATE TABLE IF NOT EXISTS shuyuan_sources (
  id serial PRIMARY KEY, source_url text NOT NULL UNIQUE, name text NOT NULL DEFAULT '',
  group_name text NOT NULL DEFAULT '', source jsonb NOT NULL, disabled_at timestamptz,
  last_error text NOT NULL DEFAULT '', updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS shuyuan_meta (
  id int PRIMARY KEY DEFAULT 1, collections jsonb NOT NULL DEFAULT '[]', refreshed_at timestamptz
);
INSERT INTO shuyuan_meta(id) VALUES(1) ON CONFLICT(id) DO NOTHING;
CREATE TABLE IF NOT EXISTS labeled_books (
  id serial PRIMARY KEY, title text NOT NULL, author text NOT NULL DEFAULT '', category text NOT NULL DEFAULT '',
  finish_status text NOT NULL DEFAULT '', source_site text NOT NULL DEFAULT '', source_url text NOT NULL DEFAULT '',
  chars_labeled int NOT NULL DEFAULT 0, labels jsonb NOT NULL DEFAULT '{}', labeled_at timestamptz NOT NULL DEFAULT now(),
  primary_genre text NOT NULL DEFAULT '', sub_tags jsonb NOT NULL DEFAULT '[]', quality float8
);
ALTER TABLE labeled_books ADD COLUMN IF NOT EXISTS source_url text NOT NULL DEFAULT '';
ALTER TABLE labeled_books ADD COLUMN IF NOT EXISTS primary_genre text NOT NULL DEFAULT '';
ALTER TABLE labeled_books ADD COLUMN IF NOT EXISTS sub_tags jsonb NOT NULL DEFAULT '[]';
ALTER TABLE labeled_books ADD COLUMN IF NOT EXISTS quality float8;
CREATE UNIQUE INDEX IF NOT EXISTS labeled_books_title_author_idx ON labeled_books(lower(title),lower(author));

CREATE TABLE IF NOT EXISTS download_tasks (
  id serial PRIMARY KEY, book_id int NOT NULL, title text NOT NULL, author text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'pending', source_url text NOT NULL DEFAULT '',
  chapters_total int NOT NULL DEFAULT 0, chapters_done int NOT NULL DEFAULT 0,
  chars_total int NOT NULL DEFAULT 0, error text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
DO $$ DECLARE bad_ids text; BEGIN
  SELECT string_agg(id::text,',' ORDER BY id) INTO bad_ids FROM download_tasks
  WHERE book_id IS NULL OR title IS NULL OR author IS NULL OR status IS NULL OR source_url IS NULL
    OR chapters_total IS NULL OR chapters_done IS NULL OR chars_total IS NULL OR error IS NULL
    OR created_at IS NULL OR updated_at IS NULL;
  IF bad_ids IS NOT NULL THEN
    RAISE EXCEPTION 'download_tasks has NULL required values; record ids: %', bad_ids;
  END IF;
END $$;
ALTER TABLE download_tasks ALTER COLUMN book_id SET NOT NULL, ALTER COLUMN title SET NOT NULL,
  ALTER COLUMN author SET DEFAULT '', ALTER COLUMN author SET NOT NULL,
  ALTER COLUMN status SET DEFAULT 'pending', ALTER COLUMN status SET NOT NULL,
  ALTER COLUMN source_url SET DEFAULT '', ALTER COLUMN source_url SET NOT NULL,
  ALTER COLUMN chapters_total SET DEFAULT 0, ALTER COLUMN chapters_total SET NOT NULL,
  ALTER COLUMN chapters_done SET DEFAULT 0, ALTER COLUMN chapters_done SET NOT NULL,
  ALTER COLUMN chars_total SET DEFAULT 0, ALTER COLUMN chars_total SET NOT NULL,
  ALTER COLUMN error SET DEFAULT '', ALTER COLUMN error SET NOT NULL,
  ALTER COLUMN created_at SET DEFAULT now(), ALTER COLUMN created_at SET NOT NULL,
  ALTER COLUMN updated_at SET DEFAULT now(), ALTER COLUMN updated_at SET NOT NULL;

CREATE TABLE IF NOT EXISTS source_read_catalogs (
  id text PRIMARY KEY, payload jsonb NOT NULL, expires_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS source_read_catalogs_expiry_idx ON source_read_catalogs(expires_at);
CREATE TABLE IF NOT EXISTS profile_seed_audit (
  id bigserial PRIMARY KEY, user_id int NOT NULL, previous_version text NOT NULL,
  saved_version text NOT NULL, added_titles jsonb NOT NULL, removed_titles jsonb NOT NULL,
  previous_seeds jsonb NOT NULL, saved_seeds jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS profile_seed_audit_user_time_idx ON profile_seed_audit(user_id,created_at DESC);
CREATE TABLE IF NOT EXISTS llm_usage (
  id bigserial PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(),
  phase text NOT NULL CHECK (phase IN ('find_recall','find_rerank','profile','feedback')),
  model text NOT NULL, prompt_tokens bigint NOT NULL DEFAULT 0 CHECK(prompt_tokens>=0),
  completion_tokens bigint NOT NULL DEFAULT 0 CHECK(completion_tokens>=0), total_tokens bigint CHECK(total_tokens>=0),
  cache_tokens bigint NOT NULL DEFAULT 0 CHECK(cache_tokens>=0), usage_missing boolean NOT NULL DEFAULT true,
  request_id text, usage_details jsonb NOT NULL DEFAULT '{}'
);
ALTER TABLE llm_usage ADD COLUMN IF NOT EXISTS request_id text;
ALTER TABLE llm_usage ADD COLUMN IF NOT EXISTS total_tokens bigint CHECK(total_tokens>=0);
ALTER TABLE llm_usage ADD COLUMN IF NOT EXISTS usage_details jsonb NOT NULL DEFAULT '{}';
-- 老实例的 total_tokens 可能是在没有约束的版本里加的；补齐到 src/lib/db.ts 的声明。
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='llm_usage'::regclass AND contype='c'
      AND pg_get_constraintdef(oid) LIKE '%total_tokens%') THEN
    ALTER TABLE llm_usage ADD CONSTRAINT llm_usage_total_tokens_check CHECK (total_tokens >= 0);
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS llm_usage_phase_created_at_idx ON llm_usage(phase,created_at DESC);

INSERT INTO auth_schema_migrations(version) VALUES(1),(2),(3),(4) ON CONFLICT(version) DO NOTHING;
